// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeecoizuyxprjndgrxwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlZWNvaXp1eXhwcmpuZGdyeHdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTc2NjAsImV4cCI6MjA2NDc3MzY2MH0.cf3N0OS4-4JzWVjgRE6uVio3MR-5CMNX9FUotxwmnQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);